## Data Preprocessing

In [1]:
import pandas as pd

In [13]:
df=pd.read_csv("../data/raw/placement.csv")

In [5]:
df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [14]:
##student id is useless
df=df.drop("StudentID", axis=1)

In [15]:
df.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CGPA                       10000 non-null  float64
 1   Internships                10000 non-null  int64
 2   Projects                   10000 non-null  int64
 3   Workshops/Certifications   10000 non-null  int64
 4   AptitudeTestScore          10000 non-null  int64
 5   SoftSkillsRating           10000 non-null  float64
 6   ExtracurricularActivities  10000 non-null  str
 7   PlacementTraining          10000 non-null  str
 8   SSC_Marks                  10000 non-null  int64
 9   HSC_Marks                  10000 non-null  int64
 10  PlacementStatus            10000 non-null  str
dtypes: float64(2), int64(6), str(3)
memory usage: 859.5 KB

In [19]:
df.select_dtypes(include="str").columns

Index(['ExtracurricularActivities', 'PlacementTraining', 'PlacementStatus'], dtype='str')

In [22]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

columns=df.select_dtypes(include="str").columns

for col in columns:
    df[col]=le.fit_transform(df[col])

In [23]:
df.head()

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,7.5,1,1,1,65,4.4,0,0,61,79,0
1,8.9,0,3,2,90,4.0,1,1,78,82,1
2,7.3,1,2,2,82,4.8,1,0,79,80,0
3,7.5,1,1,2,85,4.4,1,1,81,80,1
4,8.3,1,2,2,86,4.5,1,1,74,88,1

In [24]:
X=df.drop("PlacementStatus",axis=1)
y=df["PlacementStatus"]

In [25]:
print(X.shape)
print(y.shape)

(10000, 10)
(10000,)

In [28]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest,ytrain,ytest=train_test_split(
                            X,
                            y,
                            test_size=0.2,
                            random_state=42
                        )

In [29]:
print(Xtrain.shape)
print(Xtest.shape)

(8000, 10)
(2000, 10)

## Scaling (so as to make features comparable)

In [30]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
#fit_transform learns from the giver data and transforms
Xtrain_scaled=scaler.fit_transform(Xtrain)
#transform just apllies what it learnt from the previously given data to transform the given data
Xtest_scaled=scaler.transform(Xtest)

In [32]:
print(Xtrain_scaled.shape)
print(Xtest_scaled.shape)

(8000, 10)
(2000, 10)